### ISSUE TITLE
Exception throws, While starting Aquarium with 'docker-compose up'

### ISSUE THREAD

**Issue by Mideen** [TeamHG-Memex/aquarium#16]
I tried with Aquarium, While installation when I use "docker-compose up" to start the Splash, It throws the following exception.

> Traceback (most recent call last):
File "/usr/local/bin/docker-compose", line 11, in 
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 71, in main
command()
File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 124, in perform_command
project = project_from_options('.', options)
File "/usr/local/lib/python2.7/dist-packages/compose/cli/command.py", line 41, in project_from_options
compatibility=options.get('--compatibility'),
File "/usr/local/lib/python2.7/dist-packages/compose/cli/command.py", line 121, in get_project
host=host, environment=environment
File "/usr/local/lib/python2.7/dist-packages/compose/cli/command.py", line 92, in get_client
environment=environment, tls_version=get_tls_version(environment)
File "/usr/local/lib/python2.7/dist-packages/compose/cli/docker_client.py", line 127, in docker_client
client = APIClient(**kwargs)
File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 113, in init
config_dict=self._general_configs
TypeError: load_config() got an unexpected keyword argument 'config_dict'

Details
Machine : Linux (ubuntu 14.04)
Python 2.7.6
Docker version 18.06.0-ce, build 0ffa825
docker-compose version 1.22.0, build f46880f

Please help us to solve this issue.

**Comment by lopuhin** [comment]
I think this is a generic docker-compose or docker issue, unrelated to this project, see e.g. https://github.com/docker/docker-py/issues/1916

**Comment by Mideen** [comment]
I fixed this issue by reinstalling docker and docker-compose. Thanks for your help  @lopuhin
