### ISSUE TITLE
unexpected keyword argument 'real_url'

### ISSUE THREAD

**Issue by nicoayci** [TeamHG-Memex/aquarium#25]
Hi,
I am getting the error below with Aquarium (tried with Splash 3.0 and 3.3.1).
In this case with the most basic script to scrape google info.
The same code works when using splash without Aquarium.
Same problem occurs whether Aquarium is on localhost or somewhere else.
Happy to try to provide more info upon request.

`
ERROR: Error downloading <GET http://google.com via http://localhost:8050/execute>
Traceback (most recent call last):
  File "/home/nico/Virtualenvs/lbtrain_env3.6/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/nico/Virtualenvs/lbtrain_env3.6/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "/home/nico/Virtualenvs/lbtrain_env3.6/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 http://localhost:8050/execute>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nico/Virtualenvs/lbtrain_env3.6/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/nico/Virtualenvs/lbtrain_env3.6/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 53, in process_response
    spider=spider)
  File "/home/nico/Virtualenvs/lbtrain_env3.6/lib/python3.6/site-packages/scrapy/downloadermiddlewares/httpcompression.py", line 47, in process_response
    response = response.replace(**kwargs)
  File "/home/nico/Virtualenvs/lbtrain_env3.6/lib/python3.6/site-packages/scrapy_splash/response.py", line 43, in replace
    return cls(*args, **kwargs)
  File "/home/nico/Virtualenvs/lbtrain_env3.6/lib/python3.6/site-packages/scrapy/http/response/text.py", line 31, in __init__
    super(TextResponse, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'real_url'
`

**Comment by died14** [comment]
@nicoayci Have you managed to solve your issue? I'm having the same error, which only occurs when using aquarium.

**Comment by MlataIbrahim** [comment]
i have the same issue
